const groups=['BSP','Vibers','BackBenchers','Captain Code','Ocean Four','BHoods'];
const symbols=['B','V','BB','</>','O4','BH'];
const totals=Object.fromEntries(groups.map(g=>[g,0]));let total=0,count=0,busy=false;
const money=n=>'K'+new Intl.NumberFormat('en-PG',{maximumFractionDigits:2}).format(n);
const form=document.querySelector('form'),group=document.querySelector('#group'),amount=document.querySelector('#amount'),submit=document.querySelector('#submit'),dialog=document.querySelector('#success');
groups.forEach((g,i)=>{const option=new Option(g,g);group.add(option);const card=document.createElement('a');card.href='#donate';card.className='team-card';const icon=document.createElement('span');icon.className='team-symbol';icon.textContent=symbols[i];const title=document.createElement('h3');title.textContent=g;const sum=document.createElement('span');sum.className='team-total';sum.dataset.group=g;sum.textContent='K0 demo donations';const cta=document.createElement('strong');cta.textContent='Support this crew ↗';card.append(icon,title,sum,cta);card.addEventListener('click',()=>{group.value=g;});document.querySelector('#team-grid').append(card);});
function syncAmount(){document.querySelectorAll('[data-amount]').forEach(b=>{const selected=Number(b.dataset.amount)===Number(amount.value);b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});submit.firstChild.textContent=`Donate ${Number(amount.value)>0?money(Number(amount.value)):'your amount'} — demo `;}
document.querySelectorAll('[data-amount]').forEach(b=>b.addEventListener('click',()=>{amount.value=b.dataset.amount;syncAmount();}));amount.addEventListener('input',syncAmount);syncAmount();
function completeDonation(g,n,name){if(!groups.includes(g)||!Number.isFinite(n)||n<1||n>100000||Math.abs(n*100-Math.round(n*100))>0.00001)throw Error('Choose a valid group and an amount from K1 to K100,000 with at most two decimal places.');totals[g]=Math.round((totals[g]+n)*100)/100;total=Math.round((total+n)*100)/100;count++;document.querySelector('#raised').textContent=money(total);document.querySelector('#donation-count').textContent=`${count} demo donation${count===1?'':'s'}`;document.querySelector('#percent').textContent=`${Math.round(total/10000*100)}%`;document.querySelector('#progress').style.width=`${Math.min(100,total/10000*100)}%`;document.querySelectorAll('.team-total').forEach(e=>e.textContent=money(totals[e.dataset.group])+' demo donations');document.querySelector('#thanks').textContent=`Congratulations${name?', '+String(name).trim().slice(0,70):''}! Your ${money(n)} demo donation for ${g} is helping us imagine a brighter future. Thank you for cheering on School for Coding Agents!`;document.querySelector('#receipt-amount').textContent=money(n);if(!dialog.open)dialog.showModal();if(!matchMedia('(prefers-reduced-motion: reduce)').matches){for(let i=0;i<32;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'%';c.style.background=i%2?'#173dbe':'#ed3f49';c.style.animationDelay=Math.random()*.6+'s';dialog.append(c);setTimeout(()=>c.remove(),4000);}}return {status:'demo_completed',group:g,amount:n,currency:'PGK',total,noMoneyCharged:true};}
form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!form.reportValidity())return;busy=true;submit.disabled=true;submit.textContent='Celebrating your kindness…';try{await new Promise(r=>setTimeout(r,550));completeDonation(group.value,Number(amount.value),document.querySelector('#donor').value);}finally{busy=false;submit.disabled=false;submit.innerHTML='Donate — demo <span>♡</span>';syncAmount();}});
document.querySelectorAll('.close,.done').forEach(b=>b.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'complete_demo_donation',title:'Complete a demo school donation',description:'Simulate a donation, update this visit’s group totals, and show congratulations. No money is charged.',inputSchema:{type:'object',properties:{group:{type:'string',enum:groups},amount:{type:'number',minimum:1,maximum:100000},name:{type:'string',maxLength:70}},required:['group','amount'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.group!=='string'||typeof input.amount!=='number'||(input.name!==undefined&&typeof input.name!=='string'))throw Error('Invalid donation input');return completeDonation(input.group,input.amount,input.name);}})).catch(()=>{});}catch{}}
